config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :requests
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :request

  enum status: { pending: 0, accepted: 1, rejected: 2 }
  validates :date, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :request_categories, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :photo, presence: true, uniqueness: true
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  has_one :booking
  has_one :request_category, dependent: :destroy
  has_many :category, through: :request_category

  validates :title, presence: true, length: { minimum: 10 }
  validates :price, presence: true, numericality: { minimum: 5 }
  validates :description, presence: true, length: { minimum: 50 }
  # validates :category, presence: true
end

app/models/request_category.rb
class RequestCategory < ApplicationRecord
  belongs_to :request
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings, dependent: :destroy
  has_many :requests, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :address, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @categories = Category.last(4)
    @requests = Request.last(3)
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: %i[show edit update destroy]

  def index
    @requests = Request.all
  end

  def show
  end

  def new
    @request = Request.new
  end

  def create
    @request = Request.new(request_params)
    @request.user = current_user
    @request_category = RequestCategory.new(
      category: Category.find(params[:request][:category_ids].to_i),
      request: @request
    )
    if @request.save && @request_category.save
      redirect_to request_path(@request)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @request.update(request_params)
    redirect_to request_path(@request)
  end

  def destroy
    @request.destroy
    redirect_to requests_path, status: :see_other
  end

  private

  def set_request
    @request = Request.find(params[:id])
  end

  def request_params
    params.require(:request).permit(:title, :description, :price, :category_ids)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AilperApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <div class="banner-content">
    <h1>Un problème d'ordinateur, de smartphone ou d'imprimante ?</h1>
    <p>Postez une annonce qui décrit votre problème et recevez de l'aide rapidement grâce à un expert Ailper</p>
    <div class="banner-buttons">
      <%= link_to 'Je crée une annonce', new_request_path, class: 'cta-white' %>
      <%= link_to 'Comment ça marche ?', '#', class: 'link-white' %>
    </div>
  </div>
</div>

<div class="categories-block">
  <h2>Les catégories les plus fréquentes</h2>
  <div class="cards-grid-categories">
    <% @categories.each do |category| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= category.photo %>)">
        <%= link_to category.name, '#', class: 'cta-blue' %>
      </div>
    <% end %>
  </div>
</div>

<div class="last-requests-block">
  <h2>Les dernières annonces</h2>
  <div class="cards-grid-requests">
    <% @requests.each do |request| %>
      <%= render 'requests/request_card', request: request %>
    <% end %>
  </div>
</div>

app/views/requests/_request_card.html.erb
<div class="card-request" data-controller="clickable-card" data-clickable-card-id-value="<%= request.id %>" data-action="click->clickable-card#click">
  <div class="card-request-user">
    <%= image_tag 'https://i.pravatar.cc/40', class: 'avatar-large' %>
    <div class="card-request-user-details">
      <p class="card-request-user-name"><%= request.user.first_name %> <%= request.user.last_name.first %>.</p>
      <p class="card-request-date">Créée le <%= request.created_at %></p>
      <p class="card-request-user-address"><%= request.user.address %></p>
    </div>
  </div>
  <div class="card-request-content">
    <h3><%= request.title %></h3>
    <p><%= request.description %></p>
  </div>
  <div class="card-request-footer">
    <p class="card-request-category"><%= request.request_category.category.name %></p>
    <p class="card-request-price"><%= request.price %>€ minimum</p>
  </div>
</div>

app/views/requests/_request_form.html.erb
<div class="form-content">
  <%= simple_form_for request do |f| %>
    <%= f.input :title, label: "Titre de l'annonce" %>
    <%= f.input :description, label: "Description de l'annonce", hint: "Détaillez votre problème autant que possible pour le faire comprendre à nos experts" %>
    <div class="form-price-categories">
      <%= f.association :category, as: :radio_buttons, label: 'Catégorie de la demande', checked: 1 %>
      <%= f.input :price, label: 'Prix en €', input_html: { min: 0, step: 0.5 } %>
    </div>
    <%= f.submit 'Valider', class: 'cta-blue w-100' %>
  <% end %>
</div>

app/views/requests/index.html.erb
<div class="container">
  <h1 class="text-center">Toutes les annonces</h1>
  <div class="row">
    <div class="col-10 offset-1">
      <div class="cards">
        <% @requests.each do |request| %>
          <%= render 'request_card', request: request %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/requests/new.html.erb
<div class="form-container">
  <h1>Créez une annonce pour demander de l'aide à un expert Ailper</h1>
  <%= render 'request_form', request: @request %>
</div>

app/views/requests/show.html.erb
<div class="request-show-container">
  <div class="request-show-content">
    <h1><%= @request.title %></h1>
    <p class="request-show-date">Annonce créée le <%= @request.created_at %></p>
    <p class="request-show-price">Recevez <%= @request.price %>€ minimum en contrepartie de votre aide</p>
    <h2>Description</h2>
    <p class="request-show-paragraph"><%= @request.description %></p>
    <h2>Adresse</h2>
    <p class="request-show-paragraph"><%= @request.user.address %></p>
  </div>
  <div>
    <div class="request-show-user">
      <%= image_tag 'https://i.pravatar.cc/40', class: 'avatar-large' %>
      <p><%= @request.user.first_name %> <%= @request.user.last_name.first %>.</p>
      <p>Actif depuis le <%= @request.user.created_at %></p>
      <p><%= @request.user.requests.count %> annonces postées</p>
      <%= link_to "Envoyer un message", "#", class: "cta-blue w-100" %>
      <%= link_to "Voir le numéro", "#", class: "cta-white mt-2 w-100" %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      Ailper
    <% end %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item btn-create">
          <%= link_to new_request_path, class: "cta-white" do %>
            Créer une annonce <i class="fa-solid fa-plus"></i>
          <% end %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Mes annonces", "#", class: "dropdown-item" %>
              <%= link_to "Mon compte", "#", class: "dropdown-item" %>
              <%= link_to "Me déconnecter", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Me connecter", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>